version: "3"

# volumes:
#  mongodb_volume2:

services:
  app:
    container_name: test
    restart: always
    build: .
    ports:
      - 80:3000
    links:
      - mongo # service name
    environment:
      - MONGO_CONTAINER_NAME=mongo
      - MONGO_CONTAINER_PORT=27017

  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db